### ISSUE TITLE
在Chrome浏览器是没有问题，但是我在edge浏览器和ie9-11会报错

### ISSUE THREAD

**Issue by webzhd** [yanhaijing/template-loader#1]
![image](https://user-images.githubusercontent.com/23025883/45729575-93787600-bbff-11e8-95ca-ae3f2ac1e61b.png)

**Comment by yanhaijing** [comment]
可不可以贴一下你的 template？？？
还有编译后的代码

```
"template_js": "^0.6.1",
"templatejs-loader": "^0.1.1"，
"webpack": "^4.1.0",
```
